Dream-Transcendence/ft_transcendence

- packages/client/public/index.html
- packages/client/src/App.tsx
- packages/client/src/components/bar/NavigationBar.tsx
- packages/client/src/components/button/icon/LogoutButton.tsx
- packages/client/src/components/input/SearchBox.tsx
- packages/client/src/pages/ChatroomPage.tsx
- packages/client/src/pages/ProfilePage.tsx
- nav bar 안에 너무 많은 컴포넌트들이 구현되어 있어, 분리하는 작업을 할 필요성을 느낌
- Navbar안에 있던 searchbox를 분리하였습니다
> 📈 perf(client): devide search bar from Navbar

- packages/client/src/components/button/switch/SecondAuth.tsx
- packages/client/src/components/list/ListGenerate.tsx
- packages/client/src/components/text/ProfileNicname.tsx
- packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
- packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
추가 수정사항 업데이트 필요함
- 이중 인증 UI 추가
- UserInfo UI 배치 변경
> ✨ fix(client): create avatar, profile component

- packages/client/src/App.tsx
- packages/client/src/atoms/TextBox.tsx
- packages/client/src/components/button/block/ButtonCompenent.tsx
- packages/client/src/modules/ProfileSection/ProfileChatRoomBox.tsx
- packages/client/src/modules/ProfileSection/UserProfileBox.tsx
- packages/client/src/organisms/GameCreateSection/GameMap.tsx
- packages/client/src/pages/GameLodingPage.tsx
- packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
game lodingpage design 구현하였습니다.
"feat #73"
game loding page의 디자인과 레이아웃 규격을 미리 잡아 놓고자 하였습니다.
GameLodingPage및 하위 컴포넌트를 추가하였습니다.
TextBox컴포넌트에 텍스트 색을 props로 전달 할 수 있도록 하였습니다.
버튼의 텍스트 색상을 createTheme로 버튼 컴포넌트에 구현한 뒤 props로 원하는 값을 전달하여 변경하고자 하였으나 잘 안되었습니다.
> ✨ feat(client): game loding page 구현 ("feat #73")

- .eslintrc.js
- package.json
- packages/client/package.json
- packages/client/src/App.tsx
- yarn.lock
- 코드 작성을 위해 recoil 설치 및 세팅필요
- recoil 설치 및 세팅
> feat(common): setting for recoil

- packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
- packages/client/src/organisms/ChatMainSection/ChatRoomList.tsx
- packages/client/src/pages/ChatChannelPage.tsx
- packages/client/src/template/ChatMainSection/ChatRoomListTemplate.tsx
- packages/client/src/texts/TextBox.tsx
- 채팅방 이동경로 수정
- 지역변수로 관리되던 state를 atom으로 빼는 작업을 하였습니다.
- text를 기반으로한 styled에서 에러를 발생시켜 span으로 수정하였습니다.
> ✨ feat(client): change state to atom

- packages/client/src/atoms/bar/NavigationBar.tsx
- packages/client/src/atoms/button/icon/CustomIconButtion.tsx
- packages/client/src/atoms/button/linkPage/LinkPageIconButton.tsx
- packages/client/src/configs/Link.url.ts
- packages/client/src/molecules/ChatSection/ChatInput.tsx
- packages/client/src/molecules/ChatSection/RoomInfoBoxPassword.tsx
- packages/client/src/molecules/ChatSection/RoomInfoChatRoomBoxFunction.tsx
- packages/client/src/molecules/ChatSection/RoomInfoDMBoxFunction.tsx
- packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
- packages/client/src/molecules/ProfileSection/UserInviteBox.tsx
- packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
- packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
- packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
- packages/client/src/pages/ChatChannelPage.tsx
- packages/client/src/pages/PingpongLayout.tsx
- packages/client/src/types/Link.type.ts
버튼 클릭 시, action을 추가하기 위해 버튼을 커스텀하였습니다.
- 채팅 페이지 구조 개선을 위한 버튼 수정
-  customButton에 action추가
> ✨ feat(client): change form of custom button

- Dockerfile
- docker-compose.yml
- closes #136
- 코드 수정 시마다 진행하는 장시간의 빌드
- 로컬 소스파일을 도커 볼륨과 연결하여, 도커에서 코드 변경 감지
> ✨ feat(server): connect local server srcs to Docker volume (#136)

- packages/client/src/index.tsx
- packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
- packages/client/src/molecules/ChatSection/RoomInfoBoxFunction.tsx
- packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
- packages/client/src/molecules/ChatSection/RoomInfoBoxPassword.tsx
- packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
- packages/client/src/organisms/ChatMainSection/ChatParticipants.tsx
- packages/client/src/organisms/ChatMainSection/ChatParticipantsList.tsx
- packages/client/src/organisms/ChatMainSection/EnteredChatRoomInfo.tsx
- packages/client/src/pages/ChatChannelPage.tsx
- packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
- packages/client/src/types/Participant.type.ts
- packages/client/src/types/Room.type.ts
- 소켓을 사용하는 작업을 제외한 채팅방 내부작업 완료
#144
> 채팅방 참여인원 컴포넌트

- Dockerfile.database
- docker-compose.yml
- packages/server/init/init.sql
- packages/server/src/database/database.providers.ts
#150
- 테스트 및 개발 속도 향상을 위한 DB 초기 값 설정
- Dockerfile.database 추가
- /packages/server/init/init.sql 파일 추가
- 도커 컨테이너 최초 실행 시, DB에 초기 값 추가
----
- closes #150
> ✨ feat(server): add .sql file to initialize data in database (#150)

- packages/client/src/atoms/input/passwordBox.tsx
- packages/client/src/atoms/radio/RadioGroupButton.tsx
- packages/client/src/molecules/ChatPopUp/SetChatRoomInvite.tsx
- packages/client/src/molecules/ChatPopUp/SetChatRoomName.tsx
- packages/client/src/molecules/ChatPopUp/SetChatRoomPassword.tsx
- packages/client/src/molecules/ChatPopUp/SetChatRoomType.tsx
- packages/client/src/molecules/ChatSidebar/CreateChatRoom.tsx
- packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
- packages/client/src/types/Room.type.ts
- 채팅방 개설 기능 구현, 초기 서버 500에러 해결 일시적 네트워크 문제
- 채팅방 제목
- 채팅방 비밀번호
- 채팅방 타입 설정
- 타입이 보호일 경우에만 비밀번호 설정가능
- 최소인원설정 
- 인원추가는 향후 검색기능 구현 후 추가할 예정
- 나가기 버튼 추가
#149
> ✨ feat(client/creatroom): create room except inviting

- packages/server/src/chats/dto/rooms.dto.ts
- packages/server/src/chats/rooms.controller.ts
- packages/server/src/chats/rooms.service.ts
> 🐛 fix(server/chat): combine getChannelInfo, getDmParticipant to get

- packages/server/src/users/users.service.ts
- API 문제 사항 식별
Users 파트
- searchFriend API: 친구 닉네임이 아닌 유저 닉네임을 찾아서 반환하던 문제 수정
- getRooms API: dmList 반환 시, 상대 유저의 이름과 이미지를 반환해야 하도록 로직 수정
----
- close #159 
- close #162
> 🐛 fix(server): searchFriend API bug & getRooms dmList to get name and image

- packages/server/src/users/user.gateway.ts
#168
- 모두에게 보내면 프론트 파트 로직 과다
- 기존에 자신을 제외한 모두에게 이벤트를 보냈으나, 친구에게만 보내도록 로직 변경
----
- close #168
> 🐛 fix(server): emit just to friends when logOn/Off (#168)

- packages/server/src/chats/dto/rooms.dto.ts
- packages/server/src/chats/rooms.service.ts
- packages/server/src/users/users.service.ts
- dmList 표시할 때, 차단 여부가 필요
- enterChannel PK conflict 발생
- 차단 여부 포함
- maxId + 1 값으로 설정하여 충돌 해결
- close #185 
- close #187
> 유저 채널 가져오기 API dmList blocked 프로퍼티 추가 & enterChannel PK conflict 해결

- packages/server/src/game/game.dto.ts
- packages/server/src/game/game.gateway.ts
- packages/server/src/game/game.service.ts
- packages/server/src/users/dto/user.dto.ts
- packages/server/src/users/user.gateway.ts
- packages/server/src/users/users.service.ts
#195
- 커스텀(1:1) 대결 초대 / 수락, 매칭 로직 필요
- User namespace - Invite/Accept/Reject 로직
- Game namespace - handleMatch() 함수 Ladder/Custom 매칭 로직 분기
---
- close #195
> ✨ feat(server): implement Custom game invitation & matching logic (#195)

- packages/server/init/init.sql
- packages/server/src/game/game.gateway.ts
- packages/server/src/game/game.module.ts
- packages/server/src/game/game.service.ts
- packages/server/src/users/dto/connect-user.dto.ts
- packages/server/src/users/dto/user.dto.ts
- packages/server/src/users/user.gateway.ts
- packages/server/src/users/users.module.ts
- packages/server/src/users/users.service.ts
…emit to all users (#206)
#206
- 유저 상태 게임 중/로그인 표시
- 프론트 요청에 따라 로그온/오프 모든 유저에게 emit
- 유저의 상태를 { userId: number, onGame: boolean } 으로 상태를 나누어 보냄
- 기존 로그인 유저 중 친구들만 필터링 하여 보냈으나, 프론트 요청 내용과 같이 모든 유저에게 보냄
---
- close #205 
- close #206
> ✨ feat(server): devide user status onGame or not & LogOn/Off sockets emit to all users

- packages/server/src/users/users.service.ts
#231
- 유저 연결해제 크래시
- 유저가 연결리스트에 있을 경우만, 삭제
> 🐛 fix(server/user): protect UserService handleDisconnect Crash (#231)

- packages/server/src/chats/rooms.service.ts
#240
- 프론트 요구사항
- enterChannel : emit 메세지에 user 객체 넣어줌
- deleteChannelParticipant: 나간 참여자의 id 보내줌
> 🐛 fix(server): edit enterChannel, deleteChannelParticipant emit message

- packages/server/src/users/users.service.ts
#242
- 중복 로그인 시, 예상 치 못한 오류 발생 가능성
- 중복 로그인을 하면 WsException 보냄
---
- closes #242
> ✨ feat(server/user): block duplcate login (#242)

- packages/server/src/game/game.service.ts
- packages/server/src/users/users.service.ts
#254
- 유저 상태 emit 필요한 부분에 추가
- 인증코드 1만 단위 생성 문제
- 각 상태 변환 위치에 changeUserStatus emit 추가
- 인증코드 100000~999999 까지 생성하도록 로직 변경
---
- close #254
> ✨ feat(server/user): add changeUserStatus emits (#254)

- Dockerfile
- docker-compose.yml
- packages/server/src/game/game.dto.ts
- packages/server/src/game/game.gateway.ts
- packages/server/src/game/game.service.ts
#257
- 일대일 게임 설정 구현
- sizeDown, speedUp 설정을 하는 코드 추가
> ✨ feat(server/game): implement game customization option (#257)

- packages/server/src/game/game.dto.ts
- packages/server/src/game/game.gateway.ts
- packages/server/src/game/game.service.ts
#260
- 이전 코드는 한 명이라도 start 이벤트를 emit하면 게임이 시작되어
나머지 한 명이 게임 준비가 되었는지 확인되지 않음
- 두 명 모두에게 emit 요청을 받았을 때 시작하게 변경
- 올바른 참가자들이 들어왔는지 검증
> 🐛 fix(server/game): start event를 참가자 전원에게 받고, 참가자가 맞는지 검증 (#260)

- packages/server/src/chats/dto/rooms.dto.ts
- packages/server/src/chats/rooms.controller.ts
- packages/server/src/chats/rooms.service.ts
- packages/server/src/users/users.entity.ts
- packages/server/src/users/users.service.ts
#261
- 채널 이미지 변경 로직(+ 업로드)
- Post chats/:roomId API 요청 시, 올린 이미지를 S3에 업로드하고 url을 저장
---
- close #261
> ✨ feat(server/chat): post channel image (#261)

- packages/client/src/atoms/profile/ChatRoomImageProfile.tsx
- packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
- packages/client/src/molecules/GameSecton/GameResultMadal.tsx
- packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
- packages/client/src/organisms/GamePlaySection/GmaePlayTheme.tsx
- packages/client/src/pages/GamePlayPage.tsx
- packages/client/src/pages/GameRoutePage.tsx
- packages/client/src/template/GameCreateSection/GamePlayTemplate.tsx
- packages/client/src/types/Game.type.ts
- packages/server/src/game/game.dto.ts
- packages/server/src/game/game.service.ts
- packages/server/src/users/users.entity.ts
백엔드와 프론트간 래더게임을 연결하였습니다.
- 백엔드 api의 완성
- 래더게임 매칭기능 구현
- 기초적인 병합완료
- 추후 에러 수정예정
> ✨ feat(client): create ladder game 레더게임 병합

- Dockerfile
- docker-compose.yml
- packages/client/src/configs/Game.type.ts
- packages/client/src/molecules/GameSecton/GameResultMadal.tsx
- packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
- packages/client/src/pages/GamePlayPage.tsx
- packages/client/src/types/Game.type.ts
- LARGE  설정값수정
- paddle 이벤트 처리 수정
- user프로필  추가
> Feat/266/merge game match and game play 게임 병합 오류를 수정하여 재업로드하였습니다.

- packages/client/src/atoms/profile/ChatRoomImageProfile.tsx
- packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
채팅방 이미지변경 하는 컴포넌트를 작성하였습니다
- 채팅방 이미지 변경하는 로직 작성 필요
- 프로필 이미지변경 로직을 토대로 이미지 변경하는 컴포넌트 작성
> ✨ feat(client): create change room image 채팅방 이미지 변경

- packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
> 🐛 fix(client): fix block self

- packages/server/src/game/game.dto.ts
- packages/server/src/game/game.service.ts
#274
- 벽을 통과하는 이슈, 퍠들을 통과하는 이슈 등등..
> 🐛 fix(server/game): modified game logic (#274)

- packages/server/src/app.filter.ts
- packages/server/src/main.ts
- packages/server/src/users/users.controller.ts
- packages/server/src/users/users.service.ts
- DB 관련 에러 발생 시, 서버 크래시
- ExceptionFilter 추가
- TypeOrm 에러 filter에 추가
- NotFound 에러 필요부분에 삽입
---
- close #259
> ✨ feat(server): TypeOrm 에러 핸들링 및 ExceptionFilter 추가

- package-lock.json
- package.json
- packages/server/src/chats/rooms.service.ts
- yarn.lock
#288
- bcrypt 오타
- 수정 완료!
---
- close #288
> 🐛 fix(server): bctypt misspell (#288)

- packages/server/src/game/game.service.ts
- packages/server/src/users/user.gateway.ts
- packages/server/src/users/users.service.ts
#298
- 프론트 요청
- acceptFriendRequest 리턴 값 추가
- handleGameSize 리턴 값 가공(key -> { title: key }
> ✨ feat(server): add and fix returns on socket (#298)

- packages/server/src/chats/rooms.controller.ts
- packages/server/src/chats/rooms.service.ts
- packages/server/src/game/game.dto.ts
- packages/server/src/game/game.gateway.ts
- packages/server/src/game/game.service.ts
#307
- 타 유저들(A, B)이 생성한 게임에 제 3의 유저(C) 관전 진입 성공.
(여기서 C는 A 나 B 둘 중 하나를 선택해서 관전함. 여기선 A를 선택하여 관전했다고 가정)
- 관전 진입 후, 타 유저들(A, B)가 게임 종료 전(점수가 3점이 되기 전), 퇴장할 경우 해당 게임(ㄱ)이 끝나지 않고 계속 남아 있는 에러발생
- 타 유저(A)가 다시 새 게임(ㄴ)을 시작하기 위해 매치에 들어가서 게임을 시작한 뒤, 제 3의 유저(C)가 A를 선택하여 해당 게임(ㄴ)관전하고자 하면 기존 끝나지 않은 게임(ㄱ)으로 들어가짐
> 🐛 fix(server/game): resolve Problems that do not end due to abstention (#307)

- packages/server/init/init.sql
- packages/server/src/chats/rooms.service.ts
- packages/server/src/game/game.service.ts
#315 
#323 
- 다른 방에 들어가있어도 소켓이 받아지는 오류
- 게임 시작 전 나갈 때 아직 생기지 않은 interval 삭제하여 생기는 오류
- 각각의 방에만 메세지가 emit되게끔 enterRoom을 했을 때 기존 room들에서 나가게 함
- 게임 시작 후 나갈 때만 interval 삭제
- room db 초기값에 title 추가하여 title에 따라 메세지를 emit하게 함
> 🐛 fix(server): 다른 방에 들어가있어도 소켓이 받아지는 오류 & 게임 시작 전 나갈 때 생기는 에러 수정

- packages/client/src/atoms/SpeedDial/SpeedDial.tsx
- packages/client/src/atoms/input/AutoCompleteSerchBox.tsx
- packages/client/src/atoms/list/styles/ListStylesCSS.tsx
- packages/client/src/atoms/profile/ChatRoomImageProfile.tsx
- packages/client/src/atoms/textPrompt/MessageBox.tsx
- packages/client/src/molecules/ChatSection/ChatInput.tsx
- packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
- packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
- packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
- packages/client/src/organisms/ChatMainSection/ChatLogList.tsx
- packages/client/src/organisms/ChatMainSection/ChatParticipantsList.tsx
- packages/client/src/organisms/ChatMainSection/EnteredChatRoomInfo.tsx
- packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
- packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
- packages/client/src/organisms/ProfilePersonal/ProfilePersonal.tsx
- packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
- packages/client/src/pages/NicknamePage.tsx
- packages/client/src/pages/ProfilePage.tsx
- packages/client/src/pages/SecondOauthPage.tsx
- packages/client/src/recoil/chat.recoil.ts
- packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
- 모의평가에 따른 에러수정
(2차 인증 설정 -> 로그아웃 -> 인증번호 요청 -> 인증번호 입력하지 않고 나가기 -> 들어가기 -> 에러)
> Fix/315/fix chat and profile component 모의 평가를 통해 발견된 에러들을 수정하였습니다.

- packages/server/src/users/dto/user.dto.ts
- packages/server/src/users/user.gateway.ts
- packages/server/src/users/users.service.ts
- 게임 초대 취소 로직 필요
- 게임 초대 취소 소켓 추가
- acceptGame 소켓 입력 값 변경
```tsx
export class ClientAcceptGameDto {
userId: number;
hostId: number;
mode: number;
}
export class CancelInviteDto {
hostId: number;
}
```
---
- close #325
> ✨ feat(server/user): add cancleInivte socket (#325)

- packages/server/src/game/game.controller.ts
- packages/server/src/game/game.service.ts
#326
- 라이브 게임 페이지 추가
- getLiveGames(/game/live-games) API 추가로 요청 시, 현재 진행 중인 게임들을 배열로 반환
> ✨ feat(server/game): add live-games get api (#326)

- packages/client/src/atoms/SpeedDial/SpeedDial.tsx
- packages/client/src/atoms/bar/NavigationBar.tsx
- packages/client/src/configs/Link.url.ts
- packages/client/src/hooks/useSearch.ts
- packages/client/src/molecules/ChatSection/InfoBoxRoomFunction.tsx
- packages/client/src/molecules/Observe/LiveObserveElement.tsx
- packages/client/src/organisms/ChatMainSection/ChatLogList.tsx
- packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
- packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
- packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
- packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
- packages/client/src/organisms/ProfileFreindList/FreindList.tsx
- packages/client/src/pages/LiveObservePage.tsx
- packages/client/src/pages/PingpongRoutePage.tsx
- packages/client/src/template/GameCreateSection/GamePlayTemplate.tsx
- observe 페이지의 필요성에 따라 추가작업
- observer 페이지 생성
- chatting error 해결
> Feat/326/game observe page 게임 관전 페이지 생성

- packages/client/src/atoms/bar/NavigationBar.tsx
- packages/client/src/atoms/button/linkPage/LinkPageIconButton.tsx
- packages/client/src/atoms/input/SearchBox.tsx
- packages/client/src/pages/LiveObservePage.tsx
- packages/client/src/pages/PageStyles/ProfilePageCss.tsx
- packages/client/src/pages/PingpongRoutePage.tsx
- packages/client/src/types/Link.type.ts
- nav바의 색변경과 컴포넌트 정렬 필요성
- 기존에 사용하던 nav바 모듈을 걷어내고 직접 만들어줌
> 💎 style(client): fix style for nav bar 네비바 모듈 걷어내기

- packages/server/src/users/users.service.ts
- 초대 취소 시, 게임 중 상태 변경
- cancelInvite 함수 내에서 setConnection(userId, false) 함수 호출
> 🐛 fix(server/user): changeUserStatus when cancelInvite called (#342)

- packages/server/src/users/users.service.ts
#350
- 상호 게임 초대 시, 수락 또는 진행 불가
- 게임 중(초대 중)인 유저 게임 초대 불가
> 🐛 fix(server/user): not to friend request each others (#350)

- packages/server/src/users/dto/user.dto.ts
- packages/server/src/users/users.controller.ts
- packages/server/src/users/users.service.ts
#353
- 프론트엔드 요청
- getFriend 함수 및 DTO를 checkFriend로 수정
---
- close #353
> 🐛 fix(server/user): getFriend to checkFriend with DTO (#353)

- packages/server/src/game/game.controller.ts
- packages/server/src/game/game.dto.ts
- packages/server/src/game/game.service.ts
#354
- 게임 존재 여부 확인 API 필요
- /game/rooms/{title} 호출 시, { isExist: boolean } 응답
---
- close #354
> ✨ feat(server/game): add api check game exist (#354)

- packages/server/src/users/dto/user.dto.ts
- packages/server/src/users/users.service.ts
#355
- Exception 포함 데이터 형태 변경
- 중복 로그인, 중복 친구 초대 시 exception 데이터 변경
- 중복 로그인 { status: 100, message: string }
- 중복 친구 초대 {status: 101, message: string }
---
- close #355
> 🐛 fix(server/user): change WsException body (#355)

- docker-compose.yml
- packages/client/src/organisms/NicknameInit/NicknameInit.tsx
- packages/client/src/pages/GamePlayPage.tsx
- packages/client/src/pages/NicknamePage.tsx
- packages/client/src/template/ChatMainSection/ChatRoomListTemplate.tsx
- 에러해결
- 닉네임 레이아웃
- api 변경에 따른 에러 업데이트
-
> 🐛 fix(client): fix nickname layout and fix error
